module.exports = {
    
    valid84: [
        {
            username: 're.directorKassandra@gmail.com',
            password: 'candice1',
            rodeoName: 'noreg cat 2',
            address: '5678 rhubard rd',
            city: 'los angelos',
            state: '@alabama',
            country: '@usa',
            zip: '90001',
            timeZone: '@denver',
            dateTime: '12/27/2018 11:00',
            description: 'yay a new race!',
            url: 'google.com',
            firstName: 'first name',
            lastName: 'last name',
            email: 're.directorKassandra@gmail.com',
            waiver: 'waiver',
            initials: 'fl',
        }
    ],
    valid85: [
        {
            username: 're.directorKassandra@gmail.com',
            password: 'candice1',
            rodeoName: 'noreg nocat 1',
            address: '5678 rhubard rd',
            city: 'los angelos',
            state: '@alabama',
            country: '@usa',
            zip: '90001',
            timeZone: '@ny',
            dateTime: '12/27/2018 11:00',
            description: 'yay a new race!',
            url: 'google.com',
            firstName: 'first name',
            lastName: 'last name',
            email: 're.directorKassandra@gmail.com',
            waiver: 'waiver',
            initials: 'fl',
            
        }
    ],
    valid86: [
       {
            username: 're.directorKassandra@gmail.com',
            password: 'candice1',
            rodeoName: 'existing category 2',
            address: '5678 rhubard rd',
            city: 'los angelos',
            state: '@alabama',
            country: '@usa',
            zip: '90001',
            timeZone: '@chicago',
            dateTime: '12/27/2018 11:00',
            description: 'yay a new race!',
            url: 'google.com',
            firstName: 'first name',
            lastName: 'last name',
            email: 're.directorKassandra@gmail.com',
            catName: 'new cat',
            catIndPrice: '20',
            partLimit: '100',
            minAge: '10',
            maxAge: '100',
            waiver: 'waiver',
            regEnds: '12/26/2018 23:00',
            initials: 'fl',
        }
    ],

    valid87: [
        {
            username: 're.directorKassandra@gmail.com',
            password: 'candice1',
            rodeoName: 'new payee category 7',
            address: '1234 w',
            city: 'birmingham',
            state: '@alabama',
            country: '@usa',
            zip: '34590',
            timeZone: '@chicago',
            dateTime: '01/27/2019 11:00',
            description: 'new race yes',
            url: 'google.com',
            firstName: 'first name',
            lastName: 'last name',
            email: 're.directorKassandra@gmail.com',
            catName:'team cat',
            cptnPrice: '12',
            teammatePrice: '10',
            maxMembers: '10',
            teamLimit: '10',
            minAge: '21',
            maxAge: '30',
            regEnds: '01/27/2019 09:00',
            waiver: 'waiver',
            entityName: 'valid',
            payeeAddress: '1234',
            payeeCity: 'provo',
            payeeState: '@georgia',
            payeeZip: '23483',
            initials: 'hi',
        }
    ],

    valid88: [
        {
            username: 're.directorKassandra@gmail.com',
            password: 'candice1',
            rodeoName: 'existing payee nocat 1',
            address: '5678 rhubard rd',
            city: 'los angelos',
            state: '@alabama',
            country: '@usa',
            zip: '90001',
            timeZone: '@phoenix',
            dateTime: '12/27/2018 11:00',
            description: 'yay a new race!',
            url: 'google.com',
            firstName: 'first name',
            lastName: 'last name',
            email: 're.directorKassandra@gmail.com',
            waiver: 'waiver',
            initials: 'fl',
        }
    ],
    valid89: [
        {
            username: 're.directorKassandra@gmail.com',
            password: 'candice1',
            rodeoName: 'new payee nocat 1',
            address: '5678 rhubard rd',
            city: 'los angelos',
            state: '@alabama',
            country: '@usa',
            zip: '90001',
            timeZone: '@phoenix',
            dateTime: '12/27/2018 11:00',
            description: 'yay a new race!',
            url: 'google.com',
            firstName: 'first name',
            lastName: 'last name',
            email: 're.directorKassandra@gmail.com',
            waiver: 'waiver',
            initials: 'fl',
        }
    ],

}